name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        # if [ -f Gopkg.toml ]; then
        #     curl https://raw.githubusercontent.com/golang/dep/5eb98b36dfc3aaa3df8d808b90ae3baad80f83b6/install.sh | sh
        #     dep ensure
        # fi
        go get -d -u github.com/golang/dep
        cd $(go env GOPATH)/src/github.com/golang/dep
        DEP_LATEST=$(git describe --abbrev=0 --tags)
        git checkout $DEP_LATEST
        go install -ldflags="-X main.version=$DEP_LATEST" ./cmd/dep
        git checkout master
        dep ensure
    - name: Build
      run: go build -v .